### ISSUE TITLE
Smart Home Panel (MQTT)

### ISSUE THREAD

**Issue by Ne0-Hack3r** [v1ckxy/ecoflow-iot-reverse#5]
Here is what I've come up with thus far in terms of linking SHP to HA via MQTT...

First, follow the instructions from @lwsrbrts in ISSUE #1 

Second, configure your mosquito.conf like this:
<img width="459" alt="image" src="https://user-images.githubusercontent.com/110427837/204121784-afdd211e-1ad3-45f5-83c2-3e69fd3a2a15.png">
Note: The format of 'topic' here is intended to obfuscate the serial number such that it only has to be entered once into the mosquito.conf and everything else can then be addresses as /ecoflow/SHP/... on the local broker. The same could be done for Delta Pro using ../DP/.. or ../DP1/.. ../DP2/.. for example.

Third, build automations for each params.id you want to monitor to place the messages for those into separate topics...
```
- id: '**random#**'
  alias: SHP - Circuits
  description: ''
  trigger:
  - platform: mqtt
    topic: ecoflow/SHP/data
    payload: 96
    value_template: '{{ value_json.params[''id''] }}'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: ecoflow/SHP/circuits
      payload: '{{trigger.payload}}'
  mode: single

- id: '**random#**'
  alias: SHP - Info
  description: ''
  trigger:
  - platform: mqtt
    topic: ecoflow/SHP/data
    payload: 2
    value_template: '{{ value_json.params[''id''] }}'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: ecoflow/SHP/info
      payload: '{{trigger.payload}}'
  mode: single

- id: '**random#**'
  alias: SHP - Limits
  description: ''
  trigger:
  - platform: mqtt
    topic: ecoflow/SHP/data
    payload: 30
    value_template: '{{ value_json.params[''id''] }}'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: ecoflow/SHP/limits
      payload: '{{trigger.payload}}'
  mode: single

- id: '**random#**'
  alias: SHP - Voltage
  description: ''
  trigger:
  - platform: mqtt
    topic: ecoflow/SHP/data
    payload: 113
    value_template: '{{ value_json.params[''id''] }}'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: ecoflow/SHP/voltage
      payload: '{{trigger.payload}}'
  mode: single

`````

Fourth, create MQTT sensors for each topic above to pull key/value pairs into entity attributes in HA:
```
  - name: SHP-Circuits
    state_topic: "ecoflow/SHP/circuits"
    qos: 0
    value_template: "on"
    json_attributes_template: "{{ value_json.params | tojson}}"
    json_attributes_topic: "ecoflow/SHP/circuits"

  - name: SHP-Info
    state_topic: "ecoflow/SHP/info"
    qos: 0
    value_template: "on"
    json_attributes_template: "{{ value_json.params | tojson}}"
    json_attributes_topic: "ecoflow/SHP/info"

  - name: SHP-Limits
    state_topic: "ecoflow/SHP/limits"
    qos: 0
    value_template: "on"
    json_attributes_template: "{{ value_json.params | tojson}}"
    json_attributes_topic: "ecoflow/SHP/limits"

  - name: SHP-Voltage
    state_topic: "ecoflow/SHP/voltage"
    qos: 0
    value_template: "on"
    json_attributes_template: "{{ value_json.params | tojson}}"
    json_attributes_topic: "ecoflow/SHP/voltage"

```
Finally, create whatever custom sensors you want using the attributes from above...

```
Here are example sensors for the power on each circuit:
# SHP - Circuit Power
  - name: "SHP Circuit 1 Power"
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    state: >- 
      {{ state_attr('sensor.shp_circuits','infoList')[0].chWatt | round(0) }}

  - name: "SHP Circuit 2 Power"
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    state: >- 
      {{ state_attr('sensor.shp_circuits','infoList')[1].chWatt | round(0) }}

  - name: "SHP Circuit 3 Power"
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    state: >- 
      {{ state_attr('sensor.shp_circuits','infoList')[2].chWatt | round(0) }}

  - name: "SHP Circuit 4 Power"
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    state: >- 
      {{ state_attr('sensor.shp_circuits','infoList')[3].chWatt | round(0) }}

  - name: "SHP Circuit 5 Power"
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    state: >- 
      {{ state_attr('sensor.shp_circuits','infoList')[4].chWatt | round(0) }}

  - name: "SHP Circuit 6 Power"
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    state: >- 
      {{ state_attr('sensor.shp_circuits','infoList')[5].chWatt | round(0) }}

  - name: "SHP Circuit 7 Power"
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    state: >- 
      {{ state_attr('sensor.shp_circuits','infoList')[6].chWatt | round(0) }}

  - name: "SHP Circuit 8 Power"
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    state: >- 
      {{ state_attr('sensor.shp_circuits','infoList')[7].chWatt | round(0) }}

  - name: "SHP Circuit 9 Power"
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    state: >- 
      {{ state_attr('sensor.shp_circuits','infoList')[8].chWatt | round(0) }}

  - name: "SHP Circuit 10 Power"
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    state: >- 
      {{ state_attr('sensor.shp_circuits','infoList')[9].chWatt | round(0) }}

  - name: "SHP PRO1 Power"
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    state: >- 
      {{ state_attr('sensor.shp_circuits','infoList')[10].chWatt | round(0) }}

  - name: "SHP PRO2 Power"
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    state: >- 
      {{ state_attr('sensor.shp_circuits','infoList')[11].chWatt | round(0) }}

  - name: "SHP ALL Circuit Power"
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    state: >- 
      {{ state_attr('sensor.shp_circuits','infoList') | sum(attribute='chWatt') | round(0) }}

```
Here are some binary sensors that might be useful:
```
# Binary Sensors
- binary_sensor:

# SHP - Status
  - name: "SHP Grid Available"
    state: >- 
      {{ state_attr('sensor.shp_info','gridSta') == 1 }}

  - name: "SHP Pro1 Connected"
    state: >- 
      {{ state_attr('sensor.shp_info','energyInfos')[0].stateBean.isConnect == 1}}

  - name: "SHP Pro1 Enabled"
    state: >- 
      {{ state_attr('sensor.shp_info','energyInfos')[0].stateBean.isEnable == 1}}

  - name: "SHP Pro2 Connected"
    state: >- 
      {{ state_attr('sensor.shp_info','energyInfos')[1].stateBean.isConnect == 1}}

  - name: "SHP Pro2 Enabled"
    state: >- 
      {{ state_attr('sensor.shp_info','energyInfos')[1].stateBean.isEnable == 1}}

```
Once you have the custom sensors you want you can use them to create dashboards with lists, gauges, etc.

![image](https://user-images.githubusercontent.com/110427837/204122221-b256a980-6162-45d7-9040-1c7bb18cea9d.png)

**Comment by Ne0-Hack3r** [comment]
I am running into some issues with regard to the ../SET topic 

If I use the following in mosquito.conf, I see payloads as I change settings in the app:
`topic "" in 0 ecoflow/SHP/set /app/<EF USER ID #>/<UPPERCASE SN#>/thing/property/set`
... but this, of course, does not allow for publishing settings changes back to the EF cloud MQTT

If, however, I use the following instead, I get strange/unpredictable results:
`topic "" both 1 ecoflow/SHP/set /app/<EF USER ID #>/<UPPERCASE SN#>/thing/property/set`
... changes made in the app will initially show up in mosquito and sometimes I can successfully publish a payload to make a change from that end but then prior changes, published by the app, seem to repeat and echo to mosquito over and over

I'm not sure if this two-way "bridged" setup is problematic or if there is something I'm not understanding about this configuration... but, at this point, it is not working for me in terms of both intercepting and publishing setting changes with MQTT Explorer pointed at the mosquito broker. Assuming I can get this kink worked out I should be able to create switches and configurable entities in HA to do things like toggle EPS mode and change charge/discharge limits on the SHP...

**Comment by lwsrbrts** [comment]
I've also noticed some oddities when attempting to configure a bridge connection for the SHP but I've not had any time to investigate further. My biggest issues was that energy usage practically doubles (in terms of what's recorded, not actual usage) when I use the `both` setting in my topic mappings.

I did a very small bit of investigation at the time and the only conclusion I had was that I was experiencing looping, where the same message is received and sent again, causing a duplication of the message. It must not be turning in to a loop storm that goes on forever but it obviously renders the values recorded by the SHP useless.

I do think that the `/set` topic has messages published to without you having to do anything in the app (perhaps try by turning off your bridge and shutting down your phone but monitor from MQTT Explorer). It's almost like it's done on the server itself as something similar to scheduled message publishing by them.

**Comment by Ne0-Hack3r** [comment]
My observation thus far is that ../set only sees messages when something changes in the app. When the app first opens it sends a ‘latestquotas’ message to ../get and the SHP places a large message with status of everything within ‘quotamap’ in ../get-reply but that exchange only appears to happen when the app starts (SHP sub-app opens). DP and D2 appear to operate similarly in terms of that ‘latestquotas’ ../get exchange at app open. 

Have you seen this kind of ‘looping’ issue when doing ‘both’ on the ../set for DP? I have not tried that yet as I still have the hassio integration working for my DPs.

**Comment by lwsrbrts** [comment]
I've not observed any issues with using `both` on the set topic for my Delta Pros no - but then I've probably not paid close enough attention to them to confirm that to be the case.

I too still have both of my Delta Pros working with the HA integration and am not forced to use MQTT for them just yet so, like you, I am interested in having the SHP in HA. Unfortunately I'm not able to devote much time to tinkering at the moment.

**Comment by Ne0-Hack3r** [comment]
I noticed that my sensor to provide "SHP ALL Circuit Power" was also including the input/output of the Delta Pros when engaged as they are part of the same list (elements 10 & 11)... In Power Shell it's easy to select part of an array and send that along the pipeline but the syntax for that was not working in YAML... I'm still on a bit of YAML/Jinja 'learning curve' so I had to dig around a bit but this is what I came up with:
```
  - name: "SHP ALL Circuit Power"
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    state: >- 
      {{ state_attr('sensor.shp_circuits','infoList')[:10] | sum(attribute='chWatt') | round(0) }}

  - name: "SHP ALL PRO Power"
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    state: >- 
      {{ state_attr('sensor.shp_circuits','infoList')[-2:] | sum(attribute='chWatt') | round(0) }}
```
As I said, syntax is a bit different than PowerShell where I might have done $X[0..9] and $X[-2..-1]
... but this gets the same job done in YAML/Jinja

**Comment by Ne0-Hack3r** [comment]
I've done a lot of refining the MQTT integration to HA for SHP... I think I have all the main settings and sensors I care about at this point and decent dashboard... I'm calling the beta complete :)

![image](https://user-images.githubusercontent.com/110427837/208370027-bf17389e-cbcc-433d-96df-6954bfdf57e9.png)

**Comment by Ne0-Hack3r** [comment]
I've gone back through and refined my configuration further eliminating the need to re-publish payloads from /app/device/property/SN (remapped to ecoflow/SHP/data in my case) to other topics... I was able to eliminate all SHP related automations except one:
```
# Automations for SHP
automation:

- id: 'EF_SHP_Limits'
  alias: SHP - Limits
  description: 'Re-Publish SHP Charge/Discharge Limits to new Topic'
  trigger:
  - platform: mqtt
    topic: ecoflow/SHP/data
    payload: 30
    value_template: '{{ value_json.params[''id''] }}'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: ecoflow/SHP/limits
      payload: '{{trigger.payload}}'
      retain: true
  mode: single
```
Since the payload with the value of charge/discharge limits is sent to ../data only when/if changed my sensor would start in an unknown state and remain there until I changed the value in the app... with the above automation re-publishing to ../limits with a retained flag, the last known value is available on the broker when sensors are re-loaded in HA... The rest of the sensors were not an issue as the SHP publishes a 'heartbeat' every 1 second with most of the data I care about and publishes a payload with circuit power, etc. every 5 seconds...

Thus the MQTT sensors looks like this:
```
  - name: SHP Charge Level
    object_id: shp_charge_level
    unique_id: shp_charge_level
    unit_of_measurement: "%"
    device_class: battery
    state_class: measurement
    state_topic: "ecoflow/SHP/limits"
    qos: 0
    value_template: >-
      {% set d = value_json.params['forceChargeHigh'] %}
      {% if d is defined %}{{d}}{%else%}{{this.state}}{%endif%}

  - name: SHP Discharge Level
    object_id: shp_discharge_level
    unique_id: shp_discharge_level
    unit_of_measurement: "%"
    device_class: battery
    state_class: measurement
    state_topic: "ecoflow/SHP/limits"
    qos: 0
    value_template: >-
      {% set d = value_json.params['discLower'] %}
      {% if d is defined %}{{d}}{%else%}{{this.state}}{%endif%}
```
and are used by number templates like this:
```
  # Number Templates
  - number:

    - name: "SHP - Charge Limit"
      unique_id: shp_charge_limit
      state: "{{ states('sensor.shp_charge_level') }}"
      icon: mdi:battery-arrow-up
      min: 50
      max: 100
      step: 1
      set_value:
      - service: mqtt.publish
        data:
          topic: ecoflow/SHP/set
          payload: '{"from":"HA","id":"{{999900000+(range(10000,99999)|random)}}","moduleType":0,"operateType":"TCP","params":{"discLower":{{states("number.shp_discharge_limit")}},"forceChargeHigh":{{value}},"cmdSet":11,"id":29},"version":"1.0"}'

    - name: "SHP - Discharge Limit"
      unique_id: shp_discharge_limit
      state: "{{ states('sensor.shp_discharge_level') }}"
      icon: mdi:battery-arrow-down-outline
      min: 0
      max: 30
      step: 1
      set_value:
      - service: mqtt.publish
        data:
          topic: ecoflow/SHP/set
          payload: '{"from":"HA","id":"{{999900000+(range(10000,99999)|random)}}","moduleType":0,"operateType":"TCP","params":{"discLower":{{value}},"forceChargeHigh":{{states("number.shp_charge_limit")}},"cmdSet":11,"id":29},"version":"1.0"}'
```
